### ISSUE TITLE
Prompt template Creation not working  

### ISSUE THREAD

**Issue by NShravanReddy** [sugarcane-ai/sugarcane-ai#19]
https://github.com/sugarcane-ai/sugarcane-ai/assets/57955129/1f5ddf8e-d34b-4f4f-8b86-31f631bab44c

<img width="757" alt="Screenshot 2023-10-23 at 7 02 15 PM" src="https://github.com/sugarcane-ai/sugarcane-ai/assets/57955129/1c0b8569-9bf6-4243-82f3-49cb6fe90d7a">

**Comment by devilankur18** [comment]
@NShravanReddy this issues have been fixed. Please test
