### ISSUE TITLE
Default loading on Package Screen

### ISSUE THREAD

**Issue by sugarcanai** [sugarcane-ai/sugarcane-ai#39]
Load first package as default package when user lands on Package Screen. Blank Screen is not right.

<img width="1232" alt="Screenshot 2023-11-02 at 9 34 18 PM" src="https://github.com/sugarcane-ai/sugarcane-ai/assets/145690494/95ff3fe6-1761-4126-a8b9-1778fc04fb4a">

**Comment by Rahul917-Kumar** [comment]
is the loader on the complete screen fine??

**Comment by devilankur18** [comment]
Fixed in  https://github.com/sugarcane-ai/sugarcane-ai/commit/135d04bcea48e58617805442f7042da805cbc39a
