### ISSUE TITLE
vercel build breaking - Error: Detected unsupported "use-node-version" in your ".npmrc".

### ISSUE THREAD

**Issue by devilankur18** [sugarcane-ai/sugarcane-ai#5]
Error: Detected unsupported "use-node-version" in your ".npmrc". Please use "engines" in your "package.json" instead.
--
16:21:42.667 | Error: Command "vercel build" exited with 1
16:21:42.709 | Command "vercel build" exited with 1

<img width="1447" alt="image" src="https://github.com/sugarcane-ai/sugarcane-ai/assets/431165/6359110f-6e91-4581-b0f1-a1d4e42be646">

**Comment by AmolShelke2** [comment]
@devilankur18  is this issue is still open? or someone fixed this

**Comment by devilankur18** [comment]
@AmolShelke2 this is closed.
