### ISSUE TITLE
On Page reload current template should be autoselected

### ISSUE THREAD

**Issue by devilankur18** [sugarcane-ai/sugarcane-ai#8]
<img width="1460" alt="image" src="https://github.com/sugarcane-ai/sugarcane-ai/assets/431165/6535e073-e4cf-46f1-a3a6-e3e0cdd69c3c">

**Comment by kvishalrj** [comment]
Can you please elaborate the issue.

**Comment by devilankur18** [comment]
This issue have been fixed
