### ISSUE TITLE
Add edit button to change the description of a package

### ISSUE THREAD

**Issue by devilankur18** [sugarcane-ai/sugarcane-ai#9]
- Add edit button, next to view and logs
- Upon click should load create package popup in edit mode, only description field is editable.
- On save, update the db.

<img width="1779" alt="image" src="https://github.com/sugarcane-ai/sugarcane-ai/assets/431165/fe7ca421-37b7-4ad0-91c7-6d4a60af6e07">

**Comment by rajveer43** [comment]
Can I work for this?
